### ISSUE TITLE
client_sw unable to copy from local system and install on remote as root

### ISSUE THREAD

**Issue by pboushy** [OneIdentity/ansible-authentication-services#40]
I have a pretty basic playbook:
```
---
- name: App (Redhat)
  hosts: app
  vars:
    client_sw_dir: "./files/vas"
    client_sw_tmp_dir: /tmp/vas
    client_sw_pkg_state:
      vasclnts: present
      dnsupdate: present
    client_sw_facts_generate: true
    client_sw_facts_verbose: true
  roles:
    - name: base_linux
    - name: oneidentity.authentication_services.client_sw
    - name: app
```

When this runs, it routinely fails on `client_sw` on `install vasclnts` with an error:
```
warning: /tmp/vas/ansible-as-client_sw/vasclnts-5.1.2-8000.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 4417450c: NOKEY\nerror: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
```

If I add `ansible_become: true` under vars, then it hangs on `software install package directory check`
Running with `-vvv` tells me that it's trying to run this command:
```
EXEC /bin/sh -c 'sudo -H -S -p "[sudo via ansible, key=REDACTED] password:" -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-REDACTED ; /usr/local/Cellar/ansible/8.2.0_2/libexec/bin/python /Users/pboushy/.ansible/tmp/ansible-tmp-1699086122.439269-52181-1725620806624/AnsiballZ_client_sw_pkgs.py'"'"' && sleep 0'
```
But the become password on my local computer is vastly different than the one on the remote.
I would expect that the software install package directory check would NOT attempt sudo.

It appears that either `become: false` needs to be added to tasks that happen locally, or `become: true` needs to be added in places that require root (i.e. installing sw)

Are there any workarounds? Or did I miss something in documentation that would resolve this?
